2021-08-29 03:33:21 info: ---------------------------------------
2021-08-29 03:33:21 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 03:33:21 info: ---------------------------------------
2021-08-29 03:33:30 error: *** Unit Test Error Report ***

  console.log
    undefined

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:29:11


2021-08-29 03:34:31 info: ---------------------------------------
2021-08-29 03:34:31 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 03:34:31 info: ---------------------------------------
2021-08-29 03:34:37 error: *** Unit Test Error Report ***

  console.log
    undefined

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:29:11


2021-08-29 03:40:45 info: ---------------------------------------
2021-08-29 03:40:45 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 03:40:45 info: ---------------------------------------
2021-08-29 03:40:51 error: *** Unit Test Error Report ***

  console.log
    undefined

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:29:11


2021-08-29 03:57:49 info: ---------------------------------------
2021-08-29 03:57:49 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 03:57:49 info: ---------------------------------------
2021-08-29 03:57:56 error: *** Unit Test Error Report ***

  console.log
    undefined

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:29:11


2021-08-29 03:59:08 info: -------------------------------------------------
2021-08-29 03:59:08 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-29 03:59:08 info: -------------------------------------------------
2021-08-29 03:59:12 info: All unit tests passed.
2021-08-29 03:59:17 info: All steps were completed successfully
2021-08-29 04:00:23 info: ---------------------------------------
2021-08-29 04:00:23 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 04:00:23 info: ---------------------------------------
2021-08-29 04:00:30 error: *** Unit Test Error Report ***

  console.log
    undefined

      at 3-UsingAPIs/Week1/homework/ex1-johnWho.js:29:13


2021-08-29 04:00:47 info: Disclaimer turned off
2021-08-29 04:07:08 info: ----------------------------------------
2021-08-29 04:07:08 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-29 04:07:08 info: ----------------------------------------
2021-08-29 04:07:12 info: All unit tests passed.
2021-08-29 04:07:16 error: *** Spell Checker Report ***

ex3-rollDice.js:63:105 - Unknown word (seperately)
ex3-rollDice.js:64:90 - Unknown word (immeadiately)
ex3-rollDice.js:67:26 - Unknown word (settimeout)

2021-08-29 04:09:24 info: ----------------------------------------
2021-08-29 04:09:24 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-29 04:09:24 info: ----------------------------------------
2021-08-29 04:09:28 info: All unit tests passed.
2021-08-29 04:09:32 error: *** Spell Checker Report ***

ex3-rollDice.js:63:105 - Unknown word (separetely)

2021-08-29 04:10:00 info: ----------------------------------------
2021-08-29 04:10:00 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-29 04:10:00 info: ----------------------------------------
2021-08-29 04:10:04 info: All unit tests passed.
2021-08-29 04:10:09 info: All steps were completed successfully
2021-08-29 04:11:03 info: ---------------------------------------
2021-08-29 04:11:03 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 04:11:03 info: ---------------------------------------
2021-08-29 04:11:09 info: All unit tests passed.
2021-08-29 04:11:14 info: All steps were completed successfully
2021-08-29 04:11:38 info: --------------------------------------------
2021-08-29 04:11:38 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:11:38 info: --------------------------------------------
2021-08-29 04:11:42 info: All unit tests passed.
2021-08-29 04:11:44 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  29:9  error  'dices' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-29 04:13:06 info: --------------------------------------------
2021-08-29 04:13:06 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:13:06 info: --------------------------------------------
2021-08-29 04:13:10 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-08-29 04:17:00 info: --------------------------------------------
2021-08-29 04:17:00 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:17:00 info: --------------------------------------------
2021-08-29 04:17:04 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: function is not iterable (cannot read property Symbol(Symbol.iterator))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-08-29 04:17:06 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  29:9  error  'dices' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2021-08-29 04:17:58 info: --------------------------------------------
2021-08-29 04:17:58 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:17:58 info: --------------------------------------------
2021-08-29 04:18:02 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-08-29 04:19:11 info: --------------------------------------------
2021-08-29 04:19:11 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:19:11 info: --------------------------------------------
2021-08-29 04:19:15 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-08-29 04:21:41 info: --------------------------------------------
2021-08-29 04:21:41 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 04:21:41 info: --------------------------------------------
2021-08-29 04:21:45 info: All unit tests passed.
2021-08-29 04:21:50 info: All steps were completed successfully
2021-08-29 07:59:25 info: --------------------------------------------
2021-08-29 07:59:25 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 07:59:25 info: --------------------------------------------
2021-08-29 07:59:30 info: All unit tests passed.
2021-08-29 07:59:34 info: All steps were completed successfully
2021-08-29 08:00:20 info: --------------------------------------------
2021-08-29 08:00:20 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 08:00:20 info: --------------------------------------------
2021-08-29 08:00:24 info: All unit tests passed.
2021-08-29 08:00:29 info: All steps were completed successfully
2021-08-29 08:04:10 info: ---------------------------------------
2021-08-29 08:04:10 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-08-29 08:04:10 info: ---------------------------------------
2021-08-29 08:04:16 info: All unit tests passed.
2021-08-29 08:04:21 info: All steps were completed successfully
2021-08-29 08:04:31 info: -------------------------------------------------
2021-08-29 08:04:31 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-08-29 08:04:31 info: -------------------------------------------------
2021-08-29 08:04:35 info: All unit tests passed.
2021-08-29 08:04:39 info: All steps were completed successfully
2021-08-29 08:04:50 info: ----------------------------------------
2021-08-29 08:04:50 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-29 08:04:50 info: ----------------------------------------
2021-08-29 08:04:55 info: All unit tests passed.
2021-08-29 08:04:59 info: All steps were completed successfully
2021-08-29 08:05:10 info: --------------------------------------------
2021-08-29 08:05:10 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 08:05:10 info: --------------------------------------------
2021-08-29 08:05:14 info: All unit tests passed.
2021-08-29 08:05:18 info: All steps were completed successfully
2021-08-29 08:06:39 info: ----------------------------------------
2021-08-29 08:06:39 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-08-29 08:06:39 info: ----------------------------------------
2021-08-29 08:06:43 info: All unit tests passed.
2021-08-29 08:06:47 info: All steps were completed successfully
2021-08-29 08:17:21 info: --------------------------------------------
2021-08-29 08:17:21 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 08:17:21 info: --------------------------------------------
2021-08-29 08:17:25 info: All unit tests passed.
2021-08-29 08:17:29 error: *** Spell Checker Report ***

ex4-pokerDiceAll.js:47:45 - Unknown word (fullfillment)

2021-08-29 08:17:42 info: --------------------------------------------
2021-08-29 08:17:42 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 08:17:42 info: --------------------------------------------
2021-08-29 08:17:46 info: All unit tests passed.
2021-08-29 08:17:50 error: *** Spell Checker Report ***

ex4-pokerDiceAll.js:47:45 - Unknown word (fullfilment)

2021-08-29 08:18:00 info: --------------------------------------------
2021-08-29 08:18:00 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-08-29 08:18:00 info: --------------------------------------------
2021-08-29 08:18:04 info: All unit tests passed.
2021-08-29 08:18:08 info: All steps were completed successfully
2021-08-29 08:21:45 info: ----------------------------------------------
2021-08-29 08:21:45 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-08-29 08:21:45 info: ----------------------------------------------
2021-08-29 08:21:49 info: All unit tests passed.
2021-08-29 08:21:53 info: All steps were completed successfully
2021-09-01 03:15:39 info: ---------------------------------------------
2021-09-01 03:15:39 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-01 03:15:39 info: ---------------------------------------------
2021-09-01 03:15:48 error: *** Unit Test Error Report ***

  console.error
    Error: Uncaught [ReferenceError: fetch is not defined]
        at reportException (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:341:9)
        at invokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
        at EventTargetImpl._dispatch (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
        at fireAnEvent (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\helpers\events.js:18:36)
        at Document.<anonymous> (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\browser\Window.js:916:9)
        at Document.callTheUserObjectsOperation (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
        at innerInvokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
        at invokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
        at DocumentImpl._dispatch (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
        at fireAnEvent (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\helpers\events.js:18:36)
        at dispatchEvent (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:476:9)
        at C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:481:11
        at new Promise (<anonymous>)
        at onLoad (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:479:14)
        at Object.check (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:76:23)
        at C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:83:27
        at processTicksAndRejections (node:internal/process/task_queues:96:5) ReferenceError: fetch is not defined
        at requestData (file:///C:/Users/Gebruiker/Desktop/Homework-class33/3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js:21:3)
        at main (file:///C:/Users/Gebruiker/Desktop/Homework-class33/3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js:43:3)
        at callTheUserObjectsOperation (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
        at innerInvokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
        at invokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
        at EventTargetImpl._dispatch (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
        at fireAnEvent (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\helpers\events.js:18:36)
        at Document.<anonymous> (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\browser\Window.js:916:9)
        at Document.callTheUserObjectsOperation (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
        at innerInvokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)


2021-09-01 03:41:16 info: ---------------------------------------------
2021-09-01 03:41:16 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-01 03:41:16 info: ---------------------------------------------
2021-09-01 03:41:22 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-programmerFun.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js
  programmerFun
    √ HTML should be syntactically valid (73 ms)
    √ should use `fetch()` (1 ms)
    × should use async/wait (2 ms)
    × should use try/catch

  ● programmerFun › should use async/wait

    expect(received).toBeDefined()

    Received: undefined

      47 |
      48 |   test('should use async/wait', () => {
    > 49 |     expect(state.async).toBeDefined();
         |                         ^
      50 |     expect(state.await).toBeDefined();
      51 |   });
      52 |

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:49:25)

  ● programmerFun › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      52 |
      53 |   test('should use try/catch', () => {
    > 54 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      55 |   });
      56 | });
      57 |

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex1-programmerFun.test.js:54:28)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        4.141 s, estimated 5 s
Ran all test suites matching /ex1-programmerFun.test.js/i.

2021-09-01 03:47:11 info: ---------------------------------------------
2021-09-01 03:47:11 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-01 03:47:11 info: ---------------------------------------------
2021-09-01 03:47:18 error: *** Unit Test Error Report ***

  console.error
    Unhandled error

      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)

  console.error
    ReferenceError: fetch is not defined
        at file:///C:/Users/Gebruiker/Desktop/Homework-class33/3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js:21:5
        at new Promise (<anonymous>)
        at requestData (file:///C:/Users/Gebruiker/Desktop/Homework-class33/3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js:20:10)
        at main (file:///C:/Users/Gebruiker/Desktop/Homework-class33/3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js:48:22)
        at callTheUserObjectsOperation (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
        at innerInvokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:338:25)
        at invokeEventListeners (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:274:3)
        at EventTargetImpl._dispatch (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:221:9)
        at fireAnEvent (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\living\helpers\events.js:18:36)
        at Document.<anonymous> (C:\Users\Gebruiker\Desktop\Homework-class33\node_modules\jsdom\lib\jsdom\browser\Window.js:916:9)

      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)


2021-09-01 03:52:25 info: ---------------------------------------------
2021-09-01 03:52:25 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-01 03:52:25 info: ---------------------------------------------
2021-09-01 03:52:32 info: All unit tests passed.
2021-09-01 03:52:36 info: All steps were completed successfully
2021-09-01 03:55:10 info: ---------------------------------------------
2021-09-01 03:55:10 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-01 03:55:10 info: ---------------------------------------------
2021-09-01 03:55:17 info: All unit tests passed.
2021-09-01 03:55:21 info: All steps were completed successfully
2021-09-01 05:20:52 info: -----------------------------------------
2021-09-01 05:20:52 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2021-09-01 05:20:52 info: -----------------------------------------
2021-09-01 05:20:58 info: All unit tests passed.
2021-09-01 05:21:03 info: All steps were completed successfully
2021-09-01 05:21:17 info: -----------------------------------------
2021-09-01 05:21:17 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2021-09-01 05:21:17 info: -----------------------------------------
2021-09-01 05:21:21 info: All unit tests passed.
2021-09-01 05:21:25 info: All steps were completed successfully
2021-09-01 09:00:54 info: ----------------------------------------
2021-09-01 09:00:54 info: >>> Running Unit Test `ex4-diceRace` <<<
2021-09-01 09:00:54 info: ----------------------------------------
2021-09-01 09:01:00 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-diceRace.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Dice 1 rolled off the table.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-09-01 09:01:03 error: *** ESLint Report ***

ex4-diceRace.js
  16:22  error  A constructor name should not start with a lowercase letter  new-cap

✖ 1 problem (1 error, 0 warnings)


2021-09-01 09:02:23 info: ----------------------------------------
2021-09-01 09:02:23 info: >>> Running Unit Test `ex4-diceRace` <<<
2021-09-01 09:02:23 info: ----------------------------------------
2021-09-01 09:02:27 info: All unit tests passed.
2021-09-01 09:02:32 info: All steps were completed successfully
2021-09-01 09:07:29 info: ----------------------------------------
2021-09-01 09:07:29 info: >>> Running Unit Test `ex4-diceRace` <<<
2021-09-01 09:07:29 info: ----------------------------------------
2021-09-01 09:07:34 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-diceRace.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

2021-09-01 09:28:04 info: ----------------------------------------
2021-09-01 09:28:04 info: >>> Running Unit Test `ex4-diceRace` <<<
2021-09-01 09:28:04 info: ----------------------------------------
2021-09-01 09:28:08 info: All unit tests passed.
2021-09-01 09:28:12 info: All steps were completed successfully
2021-09-02 10:31:12 info: ----------------------------------------
2021-09-02 10:31:12 info: >>> Running Unit Test `ex5-vscDebug` <<<
2021-09-02 10:31:12 info: ----------------------------------------
2021-09-02 10:31:12 warn: A unit test file was not provided.
2021-09-02 10:31:20 info: All steps were completed successfully
2021-09-03 07:55:03 info: ---------------------------------------
2021-09-03 07:55:03 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-09-03 07:55:03 info: ---------------------------------------
2021-09-03 07:55:14 info: All unit tests passed.
2021-09-03 07:55:22 error: *** Spell Checker Report ***

ex1-johnWho.js:26:63 - Unknown word (successfuly)
ex1-johnWho.js:27:114 - Unknown word (fullname)
ex1-johnWho.js:36:58 - Unknown word (firstname)
ex1-johnWho.js:38:38 - Unknown word (fullname)
ex1-johnWho.js:41:44 - Unknown word (fullname)
ex1-johnWho.js:41:68 - Unknown word (firstname)
ex1-johnWho.js:42:43 - Unknown word (fullname)
ex1-johnWho.js:43:35 - Unknown word (varaiable)

2021-09-03 07:56:43 info: ---------------------------------------
2021-09-03 07:56:43 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-09-03 07:56:43 info: ---------------------------------------
2021-09-03 07:56:53 info: All unit tests passed.
2021-09-03 07:57:00 info: All steps were completed successfully
2021-09-03 07:59:47 info: -------------------------------------------------
2021-09-03 07:59:47 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-09-03 07:59:47 info: -------------------------------------------------
2021-09-03 07:59:55 info: All unit tests passed.
2021-09-03 08:00:02 info: All steps were completed successfully
2021-09-03 08:07:44 info: ----------------------------------------
2021-09-03 08:07:44 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-09-03 08:07:44 info: ----------------------------------------
2021-09-03 08:07:51 info: All unit tests passed.
2021-09-03 08:07:59 info: All steps were completed successfully
2021-09-03 08:13:33 info: ----------------------------------------
2021-09-03 08:13:33 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-09-03 08:13:33 info: ----------------------------------------
2021-09-03 08:13:41 info: All unit tests passed.
2021-09-03 08:13:48 info: All steps were completed successfully
2021-09-03 08:15:08 info: ---------------------------------------
2021-09-03 08:15:08 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-09-03 08:15:08 info: ---------------------------------------
2021-09-03 08:15:17 info: All unit tests passed.
2021-09-03 08:15:25 info: All steps were completed successfully
2021-09-03 08:16:41 info: ----------------------------------------
2021-09-03 08:16:41 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-09-03 08:16:41 info: ----------------------------------------
2021-09-03 08:16:49 info: All unit tests passed.
2021-09-03 08:16:56 info: All steps were completed successfully
2021-09-03 08:27:45 info: ---------------------------------------------
2021-09-03 08:27:45 info: >>> Running Unit Test `ex1-programmerFun` <<<
2021-09-03 08:27:45 info: ---------------------------------------------
2021-09-03 08:27:57 info: All unit tests passed.
2021-09-03 08:28:04 info: All steps were completed successfully
2021-09-03 08:28:19 info: --------------------------------------------
2021-09-03 08:28:19 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:28:19 info: --------------------------------------------
2021-09-03 08:28:26 info: All unit tests passed.
2021-09-03 08:28:30 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  43:7   warning  'queue' is never reassigned. Use 'const' instead      no-autofix/prefer-const
  44:3   warning  Avoid `for in` loops. Prefer `Object.keys()` instead  no-restricted-syntax
  44:8   error    'dice' is not defined                                 no-undef
  45:22  error    'dice' is not defined                                 no-undef

✖ 4 problems (2 errors, 2 warnings)


2021-09-03 08:28:34 error: *** Spell Checker Report ***

ex4-pokerDiceAll.js:42:34 - Unknown word (funct)
ex4-pokerDiceAll.js:45:16 - Unknown word (funct)

2021-09-03 08:29:43 info: --------------------------------------------
2021-09-03 08:29:43 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:29:43 info: --------------------------------------------
2021-09-03 08:29:50 info: All unit tests passed.
2021-09-03 08:29:54 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  44:3   warning  Avoid `for in` loops. Prefer `Object.keys()` instead  no-restricted-syntax
  44:8   error    'dice' is not defined                                 no-undef
  45:35  error    'dice' is not defined                                 no-undef

✖ 3 problems (2 errors, 1 warning)


2021-09-03 08:30:15 info: --------------------------------------------
2021-09-03 08:30:15 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:30:15 info: --------------------------------------------
2021-09-03 08:30:22 info: All unit tests passed.
2021-09-03 08:30:26 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  44:3   warning  Avoid `for in` loops. Prefer `Object.keys()` instead  no-restricted-syntax
  44:12  warning  'dice' is never reassigned. Use 'const' instead       no-autofix/prefer-const

✖ 2 problems (0 errors, 2 warnings)


2021-09-03 08:31:01 info: --------------------------------------------
2021-09-03 08:31:01 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:31:01 info: --------------------------------------------
2021-09-03 08:31:08 info: All unit tests passed.
2021-09-03 08:31:12 error: *** ESLint Report ***

ex4-pokerDiceAll.js
  44:3  warning  Avoid `for in` loops. Prefer `Object.keys()` instead  no-restricted-syntax

✖ 1 problem (0 errors, 1 warning)


2021-09-03 08:32:19 info: --------------------------------------------
2021-09-03 08:32:19 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:32:19 info: --------------------------------------------
2021-09-03 08:32:27 info: All unit tests passed.
2021-09-03 08:32:35 info: All steps were completed successfully
2021-09-03 08:33:38 info: --------------------------------------------
2021-09-03 08:33:38 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-09-03 08:33:38 info: --------------------------------------------
2021-09-03 08:33:46 info: All unit tests passed.
2021-09-03 08:33:53 info: All steps were completed successfully
2021-09-03 08:35:18 info: ----------------------------------------------
2021-09-03 08:35:18 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-09-03 08:35:18 info: ----------------------------------------------
2021-09-03 08:35:25 info: All unit tests passed.
2021-09-03 08:35:33 info: All steps were completed successfully
2021-09-03 08:41:43 info: ----------------------------------------------
2021-09-03 08:41:43 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-09-03 08:41:43 info: ----------------------------------------------
2021-09-03 08:41:51 info: All unit tests passed.
2021-09-03 08:41:58 info: All steps were completed successfully
2021-09-03 08:43:23 info: ----------------------------------------------
2021-09-03 08:43:23 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2021-09-03 08:43:23 info: ----------------------------------------------
2021-09-03 08:43:31 info: All unit tests passed.
2021-09-03 08:43:38 info: All steps were completed successfully
